-- ============================================
-- 基金研究系统 数据库Schema
-- Database: fund_research
-- Generated: 2026-09-04 08:55:42
-- ============================================

-- Table: ai_recommendations
CREATE TABLE `ai_recommendations` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `trade_date` date NOT NULL,\n  `fund_code` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,\n  `fund_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `direction` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '买入/卖出/观望',\n  `confidence` decimal(5,2) DEFAULT NULL COMMENT '置信度(0-100)',\n  `reason` text COLLATE utf8mb4_unicode_ci COMMENT '推荐理由',\n  `signal_sources` json DEFAULT NULL COMMENT '信号源快照{rsi,macd,trend,pattern,position,flow}',\n  `final_signal` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最终信号',\n  `nav_at_recommend` decimal(10,4) DEFAULT NULL COMMENT '推荐时净值',\n  `nav_after_1d` decimal(10,4) DEFAULT NULL COMMENT '1日后净值',\n  `nav_after_3d` decimal(10,4) DEFAULT NULL COMMENT '3日后净值',\n  `nav_after_5d` decimal(10,4) DEFAULT NULL COMMENT '5日后净值',\n  `return_1d` decimal(8,4) DEFAULT NULL COMMENT '1日收益率(%)',\n  `return_3d` decimal(8,4) DEFAULT NULL COMMENT '3日收益率(%)',\n  `return_5d` decimal(8,4) DEFAULT NULL COMMENT '5日收益率(%)',\n  `is_correct` tinyint(1) DEFAULT NULL COMMENT '判断对错',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_date_fund` (`trade_date`,`fund_code`)\n) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- Table: catalyst_analysis
CREATE TABLE `catalyst_analysis` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `event_time` datetime NOT NULL COMMENT '事件发生时间',\n  `event_type` varchar(50) NOT NULL COMMENT '事件类型：财报/政策/大会/外围传导/产业新闻',\n  `title` varchar(500) NOT NULL COMMENT '事件标题',\n  `source` varchar(100) DEFAULT NULL COMMENT '信息来源：东财快讯/用户转发/主动发现',\n  `core_variable` varchar(500) NOT NULL COMMENT '核心驱动变量（不是泛泛利好XX，而是具体什么在变）',\n  `industry_chain` text COMMENT '产业链映射：核心变量→哪些环节受益',\n  `matched_funds` json NOT NULL COMMENT '匹配的基金列表及弹性排序，如 [{"code":"025209","name":"永赢半导体","match":"完美","elasticity":1,"reason":"重仓存储=HBM直接受益"}]',\n  `watchlist_only` tinyint(1) DEFAULT '1' COMMENT '1=仅在用户观察池匹配，0=从全市场发现新标的',\n  `new_fund_codes` json DEFAULT NULL COMMENT '全市场发现的新基金代码（如有）',\n  `predicted_direction` varchar(10) NOT NULL COMMENT '预测方向：利好/利空/中性',\n  `predicted_elasticity_order` varchar(500) NOT NULL DEFAULT '',\n  `confidence` tinyint DEFAULT '3' COMMENT '确信度1-5（5=实锤，1=猜测）',\n  `actual_elasticity_order` varchar(500) DEFAULT NULL COMMENT '实际弹性排序（T+1收盘后回填）',\n  `prediction_correct` tinyint(1) DEFAULT NULL COMMENT '预测是否正确：1=正确，0=错误',\n  `actual_returns` json DEFAULT NULL COMMENT '各基金T+1/T+3/T+5实际涨跌幅，如 {"025209":{"t1":4.0,"t3":null,"t5":null}}',\n  `analysis_session` varchar(100) DEFAULT NULL COMMENT '分析时的session标识（方便回溯对话）',\n  `decision_log_ref` varchar(200) DEFAULT NULL COMMENT '决策日志中的引用位置',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  KEY `idx_event_time` (`event_time`),\n  KEY `idx_event_type` (`event_type`),\n  KEY `idx_core_variable` (`core_variable`(100)),\n  KEY `idx_prediction_correct` (`prediction_correct`)\n) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='v1.5催化剂分析表：记录每次重大事件的催化匹配过程和结果验证'


-- Table: daily_attribution
CREATE TABLE `daily_attribution` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `trade_date` date NOT NULL,\n  `fund_code` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,\n  `fund_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `daily_return` decimal(8,4) DEFAULT NULL,\n  `amount` decimal(10,2) DEFAULT NULL,\n  `beta` decimal(4,2) DEFAULT NULL,\n  `market_contribution` decimal(8,4) DEFAULT NULL,\n  `excess_return` decimal(8,4) DEFAULT NULL,\n  `sector_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `sector_return` decimal(8,4) DEFAULT NULL,\n  `sector_contribution` decimal(8,4) DEFAULT NULL,\n  `related_events` text COLLATE utf8mb4_unicode_ci,\n  `conclusion` text COLLATE utf8mb4_unicode_ci,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_date_fund` (`trade_date`,`fund_code`)\n) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- Table: daily_predictions
CREATE TABLE `daily_predictions` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `prediction_date` date NOT NULL COMMENT '预测日期（周日）',\n  `target_date` date NOT NULL COMMENT '目标日期（周一到周五）',\n  `fund_code` varchar(10) NOT NULL COMMENT '基金代码',\n  `fund_name` varchar(50) DEFAULT NULL COMMENT '基金名称',\n  `predicted_nav` decimal(10,4) DEFAULT NULL COMMENT '预测净值',\n  `predicted_change_pct` decimal(6,2) DEFAULT NULL COMMENT '预测涨跌幅%',\n  `predicted_action` enum('hold','add','reduce','stop_loss','take_profit','new_buy') NOT NULL COMMENT '预测操作',\n  `action_reason` text COMMENT '操作理由',\n  `predicted_high` decimal(10,4) DEFAULT NULL COMMENT '预测最高价',\n  `predicted_low` decimal(10,4) DEFAULT NULL COMMENT '预测最低价',\n  `confidence` int DEFAULT NULL COMMENT '置信度1-5',\n  `data_sources` text COMMENT '数据来源',\n  `actual_nav` decimal(10,4) DEFAULT NULL COMMENT '实际净值',\n  `actual_change_pct` decimal(6,2) DEFAULT NULL COMMENT '实际涨跌幅%',\n  `actual_action_taken` varchar(50) DEFAULT NULL COMMENT '实际执行的操作',\n  `accuracy` enum('correct','partial','wrong','pending') DEFAULT 'pending' COMMENT '准确度',\n  `deviation_reason` text COMMENT '偏差原因',\n  `lesson_learned` text COMMENT '教训',\n  `validated_at` datetime DEFAULT NULL COMMENT '验证时间',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `idx_fund_prediction` (`prediction_date`,`target_date`,`fund_code`),\n  KEY `idx_prediction_date` (`prediction_date`),\n  KEY `idx_target_date` (`target_date`),\n  KEY `idx_fund_code` (`fund_code`),\n  KEY `idx_accuracy` (`accuracy`)\n) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='每日持仓预测'


-- Table: etf_flow_daily
CREATE TABLE `etf_flow_daily` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `trade_date` date NOT NULL,\n  `etf_code` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,\n  `etf_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `total_shares` decimal(16,2) DEFAULT NULL COMMENT '总份额（万份）',\n  `shares_change` decimal(12,2) DEFAULT NULL COMMENT '份额变化（万份）',\n  `shares_change_pct` decimal(8,4) DEFAULT NULL COMMENT '份额变化率(%)',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_date_etf` (`trade_date`,`etf_code`)\n) ENGINE=InnoDB AUTO_INCREMENT=363 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- Table: events
CREATE TABLE `events` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `event_time` datetime NOT NULL COMMENT '事件时间',\n  `event_type` varchar(50) DEFAULT NULL COMMENT '事件类型:政策/产业/财报/地缘/突发',\n  `title` varchar(500) NOT NULL COMMENT '事件标题',\n  `description` text COMMENT '事件描述',\n  `industry` varchar(100) DEFAULT NULL COMMENT '影响行业',\n  `direction` varchar(10) DEFAULT NULL COMMENT '影响方向:利好/利空/中性',\n  `intensity` tinyint DEFAULT NULL COMMENT '影响强度:1-5星',\n  `duration` varchar(20) DEFAULT NULL COMMENT '持续性:短期/中期/长期',\n  `related_funds` text COMMENT '相关基金代码JSON',\n  `market_reaction` decimal(8,4) DEFAULT NULL COMMENT '市场实际反应(行业涨跌%)',\n  `t1_return` decimal(8,4) DEFAULT NULL COMMENT 'T+1实际收益%',\n  `t3_return` decimal(8,4) DEFAULT NULL COMMENT 'T+3实际收益%',\n  `t5_return` decimal(8,4) DEFAULT NULL COMMENT 'T+5实际收益%',\n  `similar_events` text COMMENT '历史类似事件ID',\n  `source` varchar(100) DEFAULT NULL COMMENT '信息来源',\n  `verified` tinyint(1) DEFAULT '0' COMMENT '是否已验证',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  KEY `idx_event_time` (`event_time`),\n  KEY `idx_industry` (`industry`)\n) ENGINE=InnoDB AUTO_INCREMENT=523 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='结构化事件库'


-- Table: fund_sector_map
CREATE TABLE `fund_sector_map` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `fund_code` varchar(10) NOT NULL COMMENT '基金代码',\n  `fund_name` varchar(50) DEFAULT NULL COMMENT '基金名称',\n  `sector_name` varchar(50) DEFAULT NULL COMMENT '关联板块名称',\n  `sector_index_code` varchar(20) DEFAULT NULL COMMENT '板块指数代码（东财）',\n  `sector_bk_code` varchar(20) DEFAULT NULL COMMENT '板块代码（BK开头）',\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_fund` (`fund_code`)\n) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='基金关联板块映射'


-- Table: funds
CREATE TABLE `funds` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `code` varchar(10) NOT NULL COMMENT '基金代码',\n  `name` varchar(100) DEFAULT NULL COMMENT '基金名称',\n  `company` varchar(100) DEFAULT NULL COMMENT '基金公司',\n  `manager` varchar(50) DEFAULT NULL COMMENT '基金经理',\n  `manager_since` date DEFAULT NULL COMMENT '经理任职时间',\n  `fund_type` varchar(50) DEFAULT NULL COMMENT '基金类型',\n  `theme` varchar(100) DEFAULT NULL COMMENT '投资主题',\n  `benchmark` varchar(200) DEFAULT NULL COMMENT '业绩比较基准',\n  `scale` decimal(10,2) DEFAULT NULL COMMENT '规模(亿)',\n  `establish_date` date DEFAULT NULL COMMENT '成立时间',\n  `fee_c` decimal(5,4) DEFAULT NULL COMMENT 'C类费率(年)',\n  `fee_mgmt` decimal(5,4) DEFAULT NULL COMMENT '管理费(年)',\n  `fee_custody` decimal(5,4) DEFAULT NULL COMMENT '托管费(年)',\n  `fee_service` decimal(5,4) DEFAULT NULL COMMENT '销售服务费(年)',\n  `top_holdings` text COMMENT '前十大持仓JSON',\n  `sector_exposure` varchar(200) DEFAULT NULL COMMENT '行业暴露',\n  `last_updated` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `etf_code` varchar(10) DEFAULT NULL COMMENT '对应ETF代码',\n  `sectors` varchar(200) DEFAULT NULL COMMENT '行业标签，逗号分隔',\n  `is_watchlist` tinyint DEFAULT '0' COMMENT '0=持仓 1=观察列表',\n  `watchlist_reason` text COMMENT '观察理由',\n  `watchlist_conditions` text COMMENT '进场条件JSON',\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `code` (`code`),\n  KEY `idx_code` (`code`)\n) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='基金基本信息'


-- Table: improvement_log
CREATE TABLE `improvement_log` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `log_date` date NOT NULL COMMENT '记录日期',\n  `source` enum('ai_review','user_review','kol_review','monthly_stats') NOT NULL COMMENT '来源：AI复盘/用户复盘/KOL复盘/月度统计',\n  `category` enum('timing','macro','catalyst','position','execution','rule','other') NOT NULL COMMENT '错误类别：时机/宏观/催化剂/位置/执行/规则/其他',\n  `description` text NOT NULL COMMENT '具体教训描述',\n  `impact` enum('high','medium','low') DEFAULT 'medium' COMMENT '影响程度',\n  `action_taken` text COMMENT '已采取的改进措施',\n  `action_status` enum('pending','done','verified') DEFAULT 'pending' COMMENT '改进状态',\n  `related_prediction_id` int DEFAULT NULL COMMENT '关联的预测ID',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  KEY `idx_date` (`log_date`),\n  KEY `idx_category` (`category`),\n  KEY `idx_status` (`action_status`)\n) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='改进清单-结构化教训存储'


-- Table: margin_trading_daily
CREATE TABLE `margin_trading_daily` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `trade_date` date NOT NULL,\n  `fund_code` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,\n  `margin_buy` decimal(12,2) DEFAULT NULL COMMENT '融资买入额（亿）',\n  `margin_repay` decimal(12,2) DEFAULT NULL COMMENT '融资偿还额（亿）',\n  `margin_balance` decimal(12,2) DEFAULT NULL COMMENT '融资余额（亿）',\n  `short_sell` decimal(12,2) DEFAULT NULL COMMENT '融券卖出量',\n  `short_balance` decimal(12,2) DEFAULT NULL COMMENT '融券余额（亿）',\n  `total_balance` decimal(12,2) DEFAULT NULL COMMENT '融资融券余额（亿）',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_date_fund` (`trade_date`,`fund_code`)\n) ENGINE=InnoDB AUTO_INCREMENT=1001 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- Table: market_daily
CREATE TABLE `market_daily` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `trade_date` date NOT NULL,\n  `index_name` varchar(50) NOT NULL COMMENT '指数/板块名称',\n  `index_code` varchar(20) DEFAULT NULL COMMENT '指数代码',\n  `close_price` decimal(12,4) DEFAULT NULL COMMENT '收盘价',\n  `daily_return` decimal(8,4) DEFAULT NULL COMMENT '当日涨跌幅%',\n  `ma20` decimal(12,4) DEFAULT NULL COMMENT '20日均线',\n  `above_ma20` tinyint(1) DEFAULT NULL COMMENT '是否在MA20上方',\n  `volume` decimal(16,2) DEFAULT NULL COMMENT '成交量',\n  `high` decimal(12,4) DEFAULT NULL COMMENT '最高价',\n  `low` decimal(12,4) DEFAULT NULL COMMENT '最低价',\n  `open_price` decimal(12,4) DEFAULT NULL COMMENT '开盘价',\n  `prev_close` decimal(12,4) DEFAULT NULL COMMENT '昨收价',\n  `price_pattern` varchar(20) DEFAULT NULL COMMENT '价格行为形态',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_date_index` (`trade_date`,`index_name`),\n  KEY `idx_trade_date` (`trade_date`)\n) ENGINE=InnoDB AUTO_INCREMENT=538 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='每日市场数据'


-- Table: monthly_strategy
CREATE TABLE `monthly_strategy` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `strategy_month` varchar(7) NOT NULL,\n  `generated_at` datetime NOT NULL,\n  `strategy_json` json DEFAULT NULL,\n  `mainlines_json` json DEFAULT NULL,\n  `macro_calendar_json` json DEFAULT NULL,\n  `actual_mainline` varchar(100) DEFAULT NULL,\n  `actual_return_pct` decimal(6,2) DEFAULT NULL,\n  `accuracy_notes` text,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_strategy_month` (`strategy_month`)\n) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


-- Table: nav_daily
CREATE TABLE `nav_daily` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `fund_code` varchar(10) NOT NULL,\n  `trade_date` date NOT NULL,\n  `nav` decimal(10,4) DEFAULT NULL COMMENT '单位净值',\n  `acc_nav` decimal(10,4) DEFAULT NULL COMMENT '累计净值',\n  `daily_return` decimal(8,4) DEFAULT NULL COMMENT '当日涨跌幅%',\n  `return_3d` decimal(8,4) DEFAULT NULL COMMENT '近3日收益%',\n  `return_5d` decimal(8,4) DEFAULT NULL COMMENT '近5日收益%',\n  `return_10d` decimal(8,4) DEFAULT NULL COMMENT '近10日收益%',\n  `return_20d` decimal(8,4) DEFAULT NULL COMMENT '近20日收益%',\n  `high_20d` decimal(10,4) DEFAULT NULL COMMENT '近20日最高净值',\n  `low_20d` decimal(10,4) DEFAULT NULL COMMENT '近20日最低净值',\n  `drawdown_from_high` decimal(8,4) DEFAULT NULL COMMENT '从高点回撤%',\n  `consecutive_up` int DEFAULT '0' COMMENT '连涨天数',\n  `consecutive_down` int DEFAULT '0' COMMENT '连跌天数',\n  `price_pattern` varchar(20) DEFAULT NULL COMMENT '价格行为:高开高走/高开低走/低开高走/低开低走/冲高回落/探底回升/横盘',\n  `volume_change` decimal(8,4) DEFAULT NULL COMMENT '成交量变化%(相对20日均量)',\n  `position_label` varchar(30) DEFAULT NULL,\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  `etf_code` varchar(10) DEFAULT NULL COMMENT '对应ETF代码',\n  `etf_open` decimal(10,4) DEFAULT NULL COMMENT 'ETF开盘价',\n  `etf_high` decimal(10,4) DEFAULT NULL COMMENT 'ETF最高价',\n  `etf_low` decimal(10,4) DEFAULT NULL COMMENT 'ETF最低价',\n  `etf_close` decimal(10,4) DEFAULT NULL COMMENT 'ETF收盘价',\n  `etf_pattern` varchar(20) DEFAULT NULL COMMENT 'ETF形态（完整版）',\n  `ma5` decimal(10,4) DEFAULT NULL COMMENT '5日均线',\n  `ma10` decimal(10,4) DEFAULT NULL COMMENT '10日均线',\n  `ma20` decimal(10,4) DEFAULT NULL COMMENT '20日均线',\n  `ma60` decimal(10,4) DEFAULT NULL COMMENT '60日均线',\n  `rsi_6` decimal(8,4) DEFAULT NULL COMMENT '6日RSI',\n  `rsi_12` decimal(8,4) DEFAULT NULL COMMENT '12日RSI',\n  `macd_line` decimal(10,4) DEFAULT NULL COMMENT 'MACD线',\n  `signal_line` decimal(10,4) DEFAULT NULL COMMENT '信号线',\n  `macd_histogram` decimal(10,4) DEFAULT NULL COMMENT 'MACD柱状图',\n  `trend` varchar(10) DEFAULT NULL COMMENT '趋势：上升/下降/震荡',\n  `support` decimal(10,4) DEFAULT NULL COMMENT '支撑位',\n  `resistance` decimal(10,4) DEFAULT NULL COMMENT '压力位',\n  `data_source` varchar(20) DEFAULT 'fund_nav' COMMENT '数据来源: fund_nav=真实净值, etf_realtime=ETF实时估算',\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_fund_date` (`fund_code`,`trade_date`),\n  KEY `idx_trade_date` (`trade_date`),\n  KEY `idx_fund_code` (`fund_code`)\n) ENGINE=InnoDB AUTO_INCREMENT=1385 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='每日净值与计算指标'


-- Table: north_flow_daily
CREATE TABLE `north_flow_daily` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `trade_date` date NOT NULL,\n  `sh_connect_netflow` decimal(12,2) DEFAULT NULL COMMENT '沪股通净流入（亿）',\n  `sz_connect_netflow` decimal(12,2) DEFAULT NULL COMMENT '深股通净流入（亿）',\n  `total_netflow` decimal(12,2) DEFAULT NULL COMMENT '合计净流入（亿）',\n  `buy_amount` decimal(12,2) DEFAULT NULL COMMENT '买入金额',\n  `sell_amount` decimal(12,2) DEFAULT NULL COMMENT '卖出金额',\n  `is_inflow` tinyint DEFAULT NULL COMMENT '1=流入 0=流出',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `trade_date` (`trade_date`)\n) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- Table: portfolio_daily
CREATE TABLE `portfolio_daily` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `trade_date` date NOT NULL,\n  `total_invested` decimal(10,2) DEFAULT NULL COMMENT '总投入',\n  `total_value` decimal(10,2) DEFAULT NULL COMMENT '总市值',\n  `total_profit` decimal(10,2) DEFAULT NULL COMMENT '总盈亏',\n  `profit_rate` decimal(8,4) DEFAULT NULL COMMENT '收益率%',\n  `daily_return` decimal(8,4) DEFAULT NULL COMMENT '当日收益率%',\n  `max_drawdown` decimal(8,4) DEFAULT NULL COMMENT '最大回撤%',\n  `sharpe_ratio` decimal(5,2) DEFAULT NULL COMMENT '夏普比率',\n  `win_rate` decimal(5,2) DEFAULT NULL COMMENT '胜率%',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `trade_date` (`trade_date`),\n  KEY `idx_date` (`trade_date`)\n) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='每日收益表'


-- Table: position_history
CREATE TABLE `position_history` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `snapshot_date` date NOT NULL,\n  `fund_code` varchar(10) NOT NULL,\n  `fund_name` varchar(100) DEFAULT NULL,\n  `invested` decimal(10,2) DEFAULT NULL COMMENT '买入金额',\n  `market_value` decimal(10,2) DEFAULT NULL COMMENT '当前市值',\n  `weight_pct` decimal(6,2) DEFAULT NULL COMMENT '占总仓位百分比',\n  `nav_at_snapshot` decimal(10,4) DEFAULT NULL COMMENT '快照时净值',\n  `pnl` decimal(10,2) DEFAULT NULL COMMENT '浮盈亏金额',\n  `pnl_pct` decimal(8,4) DEFAULT NULL COMMENT '浮盈亏百分比',\n  `total_portfolio_value` decimal(10,2) DEFAULT NULL COMMENT '组合总市值',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_date_fund` (`snapshot_date`,`fund_code`),\n  KEY `idx_fund` (`fund_code`),\n  KEY `idx_date` (`snapshot_date`)\n) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='仓位历史快照'


-- Table: predictions
CREATE TABLE `predictions` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `prediction_date` date NOT NULL COMMENT '预测日期',\n  `prediction_type` enum('direction','entry','exit','event_impact') NOT NULL COMMENT '预测类型：方向/进场/出场/事件影响',\n  `target` varchar(50) NOT NULL COMMENT '目标：基金代码/板块/指数',\n  `prediction` text NOT NULL COMMENT '预测内容（自然语言）',\n  `reasoning` text COMMENT '预测依据（四段式：数据/消息/逻辑/账）',\n  `confidence` int DEFAULT NULL COMMENT '确信度1-5',\n  `weight` decimal(8,4) DEFAULT NULL,\n  `time_horizon` varchar(20) DEFAULT NULL COMMENT '验证周期：1d/3d/5d/1m',\n  `actual_result` text COMMENT '实际结果（验证时填）',\n  `accuracy` enum('correct','partial','wrong','pending') DEFAULT 'pending' COMMENT '验证结果',\n  `validated_at` datetime DEFAULT NULL COMMENT '验证时间',\n  `lesson_learned` text COMMENT '教训/改进点',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  `actual_direction` varchar(10) DEFAULT NULL COMMENT '实际方向: 涨/跌/平',\n  `actual_return_pct` decimal(8,4) DEFAULT NULL COMMENT '实际收益率%',\n  `verified_at` datetime DEFAULT NULL COMMENT '验证时间',\n  `is_correct` tinyint DEFAULT NULL COMMENT '1=正确 0=错误',\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `idx_prediction_unique` (`prediction_date`,`prediction_type`,`target`),\n  KEY `idx_date` (`prediction_date`),\n  KEY `idx_target` (`target`),\n  KEY `idx_accuracy` (`accuracy`)\n) ENGINE=InnoDB AUTO_INCREMENT=83 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI预测记录-三条学习线之一'


-- Table: sector_flow_daily
CREATE TABLE `sector_flow_daily` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `trade_date` date NOT NULL,\n  `sector_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,\n  `main_inflow` decimal(12,2) DEFAULT NULL COMMENT '主力流入（亿）',\n  `main_outflow` decimal(12,2) DEFAULT NULL COMMENT '主力流出（亿）',\n  `main_netflow` decimal(12,2) DEFAULT NULL COMMENT '主力净流入（亿）',\n  `retail_inflow` decimal(12,2) DEFAULT NULL COMMENT '散户流入',\n  `retail_outflow` decimal(12,2) DEFAULT NULL COMMENT '散户流出',\n  `retail_netflow` decimal(12,2) DEFAULT NULL COMMENT '散户净流入',\n  `super_large_netflow` decimal(12,2) DEFAULT NULL COMMENT '超大单净流入',\n  `large_netflow` decimal(12,2) DEFAULT NULL COMMENT '大单净流入',\n  `medium_netflow` decimal(12,2) DEFAULT NULL COMMENT '中单净流入',\n  `small_netflow` decimal(12,2) DEFAULT NULL COMMENT '小单净流入',\n  `main_pct` decimal(8,4) DEFAULT NULL COMMENT '主力净流入占比(%)',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_date_sector` (`trade_date`,`sector_name`)\n) ENGINE=InnoDB AUTO_INCREMENT=2652 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- Table: sector_return_daily
CREATE TABLE `sector_return_daily` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `trade_date` date NOT NULL,\n  `sector_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,\n  `daily_return` decimal(8,4) DEFAULT NULL COMMENT '日涨跌幅(%)',\n  `rank_int` int DEFAULT NULL COMMENT '排名',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_date_sector` (`trade_date`,`sector_name`)\n) ENGINE=InnoDB AUTO_INCREMENT=1291 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- Table: signal_resonance
CREATE TABLE `signal_resonance` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `trade_date` date NOT NULL,\n  `fund_code` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,\n  `rsi_signal` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'RSI信号：买入/卖出/中性',\n  `macd_signal` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'MACD信号：买入/卖出/中性',\n  `pattern_signal` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '形态信号：买入/卖出/中性',\n  `flow_signal` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '资金信号：买入/卖出/中性',\n  `margin_signal` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '融资信号：买入/卖出/中性',\n  `etf_signal` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ETF信号：买入/卖出/中性',\n  `total_buy` int DEFAULT NULL COMMENT '买入信号数',\n  `total_sell` int DEFAULT NULL COMMENT '卖出信号数',\n  `final_signal` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最终信号：强烈买入/买入/观望/卖出/强烈卖出',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_date_fund` (`trade_date`,`fund_code`)\n) ENGINE=InnoDB AUTO_INCREMENT=529 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- Table: signals
CREATE TABLE `signals` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `signal_date` date NOT NULL COMMENT '信号日期',\n  `source` varchar(50) NOT NULL COMMENT '信号源:老道/Hermes/用户/新闻/技术',\n  `fund_code` varchar(10) DEFAULT NULL COMMENT '相关基金',\n  `direction` varchar(20) NOT NULL COMMENT '方向:买入/卖出/关注/回避',\n  `confidence` decimal(3,2) DEFAULT NULL COMMENT '信心度:0-1',\n  `nav_at_signal` decimal(10,4) DEFAULT NULL COMMENT '信号时净值',\n  `reason` text COMMENT '信号理由',\n  `t1_return` decimal(8,4) DEFAULT NULL COMMENT 'T+1收益%',\n  `t3_return` decimal(8,4) DEFAULT NULL COMMENT 'T+3收益%',\n  `t5_return` decimal(8,4) DEFAULT NULL COMMENT 'T+5收益%',\n  `t10_return` decimal(8,4) DEFAULT NULL COMMENT 'T+10收益%',\n  `max_favorable` decimal(8,4) DEFAULT NULL COMMENT '最大有利变动%',\n  `max_adverse` decimal(8,4) DEFAULT NULL COMMENT '最大不利变动%',\n  `hold_days` int DEFAULT NULL COMMENT '建议持有天数',\n  `actual_result` decimal(8,4) DEFAULT NULL COMMENT '实际最终收益%',\n  `is_correct` tinyint(1) DEFAULT NULL COMMENT '判断是否正确',\n  `notes` text COMMENT '备注',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  KEY `idx_signal_date` (`signal_date`),\n  KEY `idx_source` (`source`),\n  KEY `idx_fund_code` (`fund_code`)\n) ENGINE=InnoDB AUTO_INCREMENT=99 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='信号源记录'


-- Table: strategy_backtest
CREATE TABLE `strategy_backtest` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `strategy_name` varchar(50) NOT NULL,\n  `fund_code` varchar(10) NOT NULL,\n  `backtest_period` varchar(50) DEFAULT NULL,\n  `total_trades` int DEFAULT NULL COMMENT '总交易次数',\n  `win_rate` decimal(5,2) DEFAULT NULL COMMENT '胜率%',\n  `avg_return` decimal(8,4) DEFAULT NULL COMMENT '平均收益率%',\n  `max_drawdown` decimal(8,4) DEFAULT NULL COMMENT '最大回撤%',\n  `sharpe_ratio` decimal(5,2) DEFAULT NULL COMMENT '夏普比率',\n  `notes` text,\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  `win_streak` int DEFAULT NULL COMMENT '最大连胜',\n  `lose_streak` int DEFAULT NULL COMMENT '最大连亏',\n  `avg_hold_days` decimal(5,1) DEFAULT NULL COMMENT '平均持仓天数',\n  `profit_factor` decimal(5,2) DEFAULT NULL COMMENT '盈亏比',\n  PRIMARY KEY (`id`),\n  KEY `idx_strategy_name` (`strategy_name`),\n  KEY `idx_fund_code` (`fund_code`)\n) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='策略回测记录'


-- Table: strategy_evolution
CREATE TABLE `strategy_evolution` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `evolution_date` date NOT NULL,\n  `trigger_event` text NOT NULL COMMENT '触发事件（什么错误/发现导致调整）',\n  `old_rule` text COMMENT '旧规则',\n  `new_rule` text NOT NULL COMMENT '新规则',\n  `expected_impact` text COMMENT '预期效果',\n  `actual_impact` text COMMENT '实际效果（后续验证）',\n  `status` enum('active','tested','retired') DEFAULT 'active',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='策略进化记录'


-- Table: trades
CREATE TABLE `trades` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `trade_date` date NOT NULL COMMENT '交易日期',\n  `sell_date` date DEFAULT NULL,\n  `fund_code` varchar(10) NOT NULL COMMENT '基金代码',\n  `fund_name` varchar(100) DEFAULT NULL COMMENT '基金名称',\n  `direction` varchar(10) NOT NULL COMMENT '买入/卖出',\n  `amount` decimal(10,2) DEFAULT NULL COMMENT '金额(元)',\n  `nav_price` decimal(10,4) DEFAULT NULL COMMENT '成交净值',\n  `reason` text COMMENT '买入/卖出理由',\n  `signal_source` varchar(50) DEFAULT NULL COMMENT '信号来源',\n  `market_state` text COMMENT '当时市场状态',\n  `hermes_judgment` text COMMENT 'Hermes当时的判断',\n  `user_judgment` text COMMENT '用户当时的判断',\n  `expected_hold_days` int DEFAULT NULL COMMENT '预期持有天数',\n  `stop_loss` decimal(8,4) DEFAULT NULL COMMENT '止损线%',\n  `take_profit` decimal(8,4) DEFAULT NULL COMMENT '止盈线%',\n  `actual_sell_nav` decimal(10,4) DEFAULT NULL COMMENT '实际卖出净值(卖出时填)',\n  `actual_return` decimal(8,4) DEFAULT NULL COMMENT '实际收益率%',\n  `hold_days` int DEFAULT NULL COMMENT '实际持有天数',\n  `max_favorable` decimal(8,4) DEFAULT NULL COMMENT '持有期最大浮盈%',\n  `max_adverse` decimal(8,4) DEFAULT NULL COMMENT '持有期最大浮亏%',\n  `fee` decimal(8,4) DEFAULT NULL COMMENT '实际费用(赎回费等)',\n  `net_return` decimal(8,4) DEFAULT NULL COMMENT '扣费后净收益%',\n  `trade_status` varchar(20) DEFAULT 'open' COMMENT 'open/closed',\n  `notes` text COMMENT '备注',\n  `analysis_scope` json DEFAULT NULL COMMENT '买入时分析覆盖维度（催化剂/宏观/位置/时机）',\n  `user_reasoning` text COMMENT '用户自己的判断依据（用户决策线）',\n  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  KEY `idx_trade_date` (`trade_date`),\n  KEY `idx_fund_code` (`fund_code`),\n  KEY `idx_trade_status` (`trade_status`)\n) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='个人交易记录'


-- Table: v_catalyst_summary
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `v_catalyst_summary` AS select `catalyst_analysis`.`id` AS `id`,`catalyst_analysis`.`event_time` AS `event_time`,`catalyst_analysis`.`event_type` AS `event_type`,left(`catalyst_analysis`.`title`,60) AS `title`,`catalyst_analysis`.`core_variable` AS `core_variable`,`catalyst_analysis`.`confidence` AS `confidence`,`catalyst_analysis`.`predicted_direction` AS `predicted_direction`,left(`catalyst_analysis`.`predicted_elasticity_order`,80) AS `predicted`,left(`catalyst_analysis`.`actual_elasticity_order`,80) AS `actual`,(case when (`catalyst_analysis`.`prediction_correct` = 1) then '✅正确' when (`catalyst_analysis`.`prediction_correct` = 0) then '❌错误' else '⏳待验证' end) AS `status`,(to_days(now()) - to_days(`catalyst_analysis`.`event_time`)) AS `days_ago` from `catalyst_analysis` order by `catalyst_analysis`.`event_time` desc


